project/inventory/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name = "inventory"

urlpatterns = [
    path("", views.index, name="index"),
    path("inventory/summary", views.summary, name="summary"),
    path("inventory/inventory", views.inventory, name="inventory"),
    path("inventory/add_item", views.add_item, name="add_item"),
    path("inventory/edit_item/<int:id>", views.edit_item, name="edit_item"),
    path("inventory/load_areas", views.load_areas, name="load_areas"),
    path("inventory/notes/<int:id>", views.notes, name="notes"),
    path(
        "inventory/export_to_excel", views.export_to_excel, name="export_to_excel"
    ),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path('maintenance/', views.maintenance, name='maintenance'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('autos/',  include('automotive.urls')),
    path('residential/',  include('residential.urls')),
    path('expense_tracking/',  include('expense_tracking.urls')),
    path('inventory/',  include('inventory.urls')),
]

project/inventory/models.py
from django.db import models
from django.utils import timezone


class MapLocation(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Map_Locations"

    def __str__(self):
        return self.name


class Area(models.Model):
    name = models.CharField(max_length=100)
    map_loc = models.ForeignKey(
        MapLocation,
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = "Areas"

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Manufacturers"

    def __str__(self):
        return self.name


class ApprovalList(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Approval_List"

    def __str__(self):
        return self.name


class Assignee(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Assignees"

    def __str__(self):
        return self.name


class ItemStatus(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Item_Status"

    def __str__(self):
        return self.name


class InventoryItem(models.Model):
    asset_id = models.CharField(
        max_length=100,
        blank=True
    )
    name = models.CharField(max_length=100)
    stat = models.ForeignKey(
        ItemStatus,
        on_delete=models.CASCADE
    )
    description = models.TextField()
    item_location = models.ForeignKey(
        MapLocation,
        on_delete=models.CASCADE
    )
    item_area = models.ForeignKey(
        Area,
        on_delete=models.CASCADE
    )
    mfg = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE
    )
    model_no = models.CharField(max_length=100)
    serial_no = models.CharField(max_length=100, blank=True, null=True)
    qty = models.IntegerField()
    total_cost = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    cost_per_item = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    assigned_to = models.ForeignKey(
        Assignee,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    approved_by = models.ForeignKey(
        ApprovalList,
        on_delete=models.CASCADE
    )
    approved_date = models.DateField()
    purchased_from = models.CharField(max_length=100, blank=True)
    purchase_date = models.DateField()
    inserted_by = models.CharField(blank=True, null=True)
    inserted_date = models.DateField()
    modified_by = models.CharField(max_length=150, blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Inventory_Items"

    def __str__(self):
        return self.name


class ItemNotes(models.Model):
    item = models.ForeignKey(
        InventoryItem,
        on_delete=models.CASCADE
    )
    comment = models.TextField()
    inserted_by = models.CharField(max_length=250)
    inserted_date = models.DateTimeField(
        default=timezone.now
    )

    class Meta:
        verbose_name_plural = "Item_Notes"

    def __str__(self):
        return self.item.name

project/inventory/forms.py
from django import forms
from .models import ItemNotes, InventoryItem


class InventoryForm(forms.ModelForm):

    class Meta:
        model = InventoryItem
        fields = (
            'asset_id',
            'name',
            'stat',
            'description',
            'item_location',
            'item_area',
            'mfg',
            'model_no',
            'serial_no',
            'qty',
            'total_cost',
            'cost_per_item',
            'assigned_to',
            'approved_by',
            'approved_date',
            'purchased_from',
            'purchase_date'
        )


class NoteForm(forms.ModelForm):

    class Meta:
        model = ItemNotes
        fields = (
            'comment',
        )

project/inventory/views.py
import logging
import csv
import datetime
import pandas as pd
import plotly.graph_objs as go

from pytz import timezone
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import (
    login, logout, authenticate, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import (
    InventoryItem,
    ItemNotes,
    ItemStatus,
    Area,
    MapLocation,
    Manufacturer,
    Assignee,
    ApprovalList
)
from .forms import (
    NoteForm,
    InventoryForm
)
from django.urls import reverse_lazy
from plotly.offline import plot
from pretty_html_table import build_table


logger = logging.getLogger(__name__)
EST = timezone('US/Eastern')


def maintenance(request):
    return render(
        request=request,
        template_name='inventory/maintenance.html')


def index(request):
    return render(request=request,
                  template_name="inventory/index.html"
                  )


@login_required
def summary(request):

    try:
        # Create dataframe from all records for specified fields
        df = pd.DataFrame(list(
            InventoryItem.objects.all().values(
                'item_location__name',
                'qty',
                'total_cost'
            )
        )
        )

        if len(df.index) == 0:
            return render(
                request=request,
                template_name='inventory/summary.html',
                context={
                    'msg': 'No records found!'
                }
            )
        else:
            #grouped_df = df.groupby(
            #    'item_location__name', as_index=False
            #    ).sum()

            grouped_df = df.groupby(
                ['item_location__name']
                ).agg({'qty': 'sum', 'total_cost': 'sum'}).reset_index()

            grouped_df.columns = [
                'Location', 'Total Number of Items', 'Total Cost'
            ]

            #grouped_df['Total Cost'] = grouped_df['Total Cost'].map(
            #    '${:,.2f}'.format)

            if len(grouped_df.index) == 0:
                return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'msg': 'No records found!'
                    }
                )
            else:

                trace_pie = go.Pie(
                    values=grouped_df['Total Number of Items'],
                    labels=grouped_df['Location'],
                    # textinfo='percent+value',
                )

                config = {
                    'responsive': True,
                    'displaylogo': False
                }

                data = [trace_pie]

                fig_pie = go.Figure(data=data)

                fig_pie.update_layout(
                    autosize=True,
                    # width=600,
                    # height=600,
                    title_text='<b>Inventory Percentage per Location</b>',
                    title_x=0.50,
                    title_y=0.95,
                    title_font=dict(size=18),
                    legend_font_size=14,
                    legend=dict(
                        orientation="h"
                    ),
                    # legend_yanchor='bottom',
                    # legend_y=0,
                    # legend_xanchor='right',
                    # legend_x=2.5,
                    # margin=dict(
                    #     l=0,
                    #     r=0,
                    #     b=0,
                    #     t=0
                    # ),
                )

                plt_div_pie = plot(
                    fig_pie, config=config, output_type='div'
                )

                return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'grouped_df': build_table(
                            grouped_df,
                            'blue_dark',
                            text_align='right'
                        ),
                        'plt_div_pie': plt_div_pie
                    }
                )

    except Exception as e:
        logging.error(f'Exception on data visualization: {e}')
        return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'msg': 'No records found!'
                    }
                )

@login_required
def inventory(request):
    #inventory_list = InventoryItem.objects.all()
    inventory_list = InventoryItem.objects.all().values(
        'id',
        'asset_id',
        'name',
        'stat__name',
        'description',
        'item_location__name',
        'item_area__name',
        'mfg__name',
        'model_no',
        'serial_no',
        'qty',
        'total_cost',
        'cost_per_item',
        'assigned_to__name',
        'approved_by__name',
        'approved_date',
        'purchased_from',
        'purchase_date',
        'inserted_by',
        'inserted_date',
        'modified_by',
        'modified_date'
    ).order_by('-purchase_date')

    return render(request=request,
                  template_name="inventory/inventory.html",
                  context={
                      'inventory_list': inventory_list
                  }
                  )


@login_required
def load_areas(request):
    loc = request.GET.get('item_location')
    areas = Area.objects.filter(map_loc=loc).order_by('name')
    return render(
        request=request,
        template_name="inventory/areasOpts.html",
        context={
            'loc': loc,
            'areas': areas
        }
    )


@login_required
def add_item(request):
    stats = ItemStatus.objects.all().values().order_by('name').values()
    areas = Area.objects.all().values().order_by('name').values()
    locations = MapLocation.objects.all().values().order_by('name').values()
    mfgs = Manufacturer.objects.all().order_by('name').values()
    assignees = Assignee.objects.all().order_by('name').values()
    approvers = ApprovalList.objects.all().order_by('name').values()

    if request.method == "POST":
        form = InventoryForm(request.POST)

        if form.is_valid():

            item_to_insert = form.save(commit=False)
            item_to_insert.stat = form.cleaned_data['stat']
            item_to_insert.asset_id = form.cleaned_data['asset_id']
            item_to_insert.name = form.cleaned_data['name']
            item_to_insert.description = form.cleaned_data['description']
            item_to_insert.item_location = form.cleaned_data['item_location']
            item_to_insert.item_area = form.cleaned_data['item_area']
            item_to_insert.mfg = form.cleaned_data['mfg']
            item_to_insert.model_no = form.cleaned_data['model_no'].upper()
            if form.cleaned_data['serial_no'] is None:
                item_to_insert.serial_no = form.cleaned_data['serial_no']
            else:
                item_to_insert.serial_no = (
                    form.cleaned_data['serial_no'].upper())
            item_to_insert.qty = form.cleaned_data['qty']
            item_to_insert.total_cost = form.cleaned_data['total_cost']
            item_to_insert.cost_per_item = form.cleaned_data['total_cost']/form.cleaned_data['qty']
            item_to_insert.assigned_to = form.cleaned_data['assigned_to']
            item_to_insert.approved_by = form.cleaned_data['approved_by']
            item_to_insert.approved_date = form.cleaned_data['approved_date']
            item_to_insert.purchased_from = form.cleaned_data['purchased_from']
            item_to_insert.purchase_date = form.cleaned_data['purchase_date']
            item_to_insert.inserted_by = request.user
            item_to_insert.inserted_date = datetime.datetime.now(tz=EST)
            item_to_insert.save()
            messages.success(
                request,
                'New inventory item added successfully!'
            )

            return redirect('inventory:inventory')

        else:
            return render(
                request=request,
                template_name="inventory/add_item.html",
                context={"form": form}
            )

    else:
        form = NoteForm()
        return render(
            request=request,
            template_name="inventory/add_item.html",
            context={
                'stats': stats,
                'areas': areas,
                'locations': locations,
                'mfgs': mfgs,
                'assignees': assignees,
                'approvers': approvers
            }
        )


@login_required
def edit_item(request, id):

    # Obtain record to edit by id
    entry_to_edit = InventoryItem.objects.get(id=id)

    # Obtain list of status in order by name, except the selected value
    # by id from the form
    stat_list = ItemStatus.objects.exclude(
        id=entry_to_edit.stat.pk
    ).order_by('name')

    # Obtain list of locations in order by name, except the selected value
    # by id from the form
    loc_list = MapLocation.objects.exclude(
        id=entry_to_edit.item_location.pk
    ).order_by('name')

    # Get area
    # current_area = entry_to_edit.location.name
    # lst = (list(current_area.split(" ")))
    # cur_area = lst[0]

    # Obtain list of areas in order by name, except the selected value
    # by id from the form
    area_list = Area.objects.filter(
        map_loc=entry_to_edit.item_location.pk).order_by('name')

    # Obtain list of manufacturers in order by name, except the selected value
    # by id from the form
    mfg_list = Manufacturer.objects.exclude(
        id=entry_to_edit.mfg.pk
    ).order_by('name')

    # Obtain list of assignees in order by name, except the selected value

project/templates/inventory/areasOpts.html
{% if loc %}
    <div id="area-select">
        <label for="item_area">Area</label>
        <select
            class="form-control form-control-sm"
            id="item_area"
            name="item_area"
        >
            <option
            selected="true"
            value="-1"
            disabled
            >
            --- Select an Area ---
            </option>
            {% for a in areas %}
                <option value="{{ a.id }}">
                    {{ a.name }}
                </option>
            {% endfor %}
        </select>
    </div>
{% endif %}

project/templates/inventory/index.html
{% extends 'inventory/layout.html' %}
{% load static %}
{% block title %}Home{% endblock %}
{% block body %}
    <main role="main">
            <header class="page-heading">
                <h1>Inventory Home</h1>
            </header>
            <section class="page-content">
                    <div class="grid-container">
                        <div id="longleaf">
                            <img
                            src="{% static  'residential/img/HomeImage.jpg' %}"
                            alt="Image of house"
                            class="responsive"
                            />
                        </div>
                    </div>
            </section>
        </main>
  </div>
{% endblock %}

project/templates/inventory/inventory.html
{% extends 'inventory/layout.html' %}
{% load static %}
{% block title %}Inventory{% endblock %}
{% block body %}
<div class="page-content">
  <div class="container-fluid">
    <legend class="border-bottom mb-4">
      Inventory
    </legend>
    <table id="inventoryTable" class="table table-sm table-hover table-responsive-sm table-bordered" width="100%">
      <thead class="table-primary">
      <tr>
        <th class="fit">ID</th>
        <th class="fit">Status</th>
        <th class="fit">Asset ID</th>
        <th class="fit">Item</th>
        <th class="fit">Description</th>
        <th class="fit">Location</th>
        <th class="fit">Area</th>
        <th class="fit">Mfg.</th>
        <th class="fit">Model #</th>
        <th class="fit">Serial #</th>
        <th class="fit">Qty</th>
        <th class="fit">Total Cost</th>
        <th class="fit">Cost/Item</th>
        <th class="fit">Assigned To</th>
        <th class="fit">Approved By</th>
        <th class="fit">Approved Date</th>
        <th class="fit">Purchased From</th>
        <th class="fit">Purchase Date</th>
        <th class="fit">Inserted By</th>
        <th class="fit">Inserted Date</th>
        <th class="fit">Modified By</th>
        <th class="fit">Modified Date</th>
        <th class="fit"></th>
        <th class="fit"></th>
      </tr>
    </thead>
    <tbody>
      {% for item in inventory_list %}
        <tr>
          <td class="fit">{{item.id}}</td>
          <td class="fit">{{item.stat__name}}</td>
          <td class="fit">{{item.asset_id}}</td>
          <td class="fit" style="text-align: left;">{{item.name}}</td>
          <td width="25%" style="text-align: left; word-wrap: break-all;">{{item.description}}</td>
          <td class="fit" style="text-align: left;">{{item.item_location__name}}</td>
          <td class="fit" style="text-align: left;">{{item.item_area__name}}</td>
          <td class="fit" style="text-align: left;">{{item.mfg__name}}</td>
          <td class="fit" style="text-align: left;">{{item.model_no}}</td>
          <td class="fit" style="text-align: left;">{{item.serial_no}}</td>
          <td class="fit">{{item.qty}}</td>
          <td class="fit" style="text-align: right;">${{item.total_cost|floatformat:2}}</td>
          <td class="fit" style="text-align: right;">${{item.cost_per_item|floatformat:2}}</td>
          <td class="fit" style="text-align: left;">{{item.assigned_to__name}}</td>
          <td class="fit" style="text-align: left;">{{item.approved_by__name}}</td>
          <td class="fit">{{item.approved_date|date:"Y/m/d"}}</td>
          <td class="fit" style="text-align: left;">{{item.purchased_from}}</td>
          <td class="fit">{{item.purchase_date|date:"Y/m/d"}}</td>
          <td class="fit" style="text-align: left;">{{item.inserted_by}}</td>
          <td class="fit">{{item.inserted_date|date:"Y/m/d"}}</td>
          <td class="fit">{{item.modified_by}}</td>
          <td class="fit">{{item.modified_date|date:"Y/m/d"}}</td>
          <td class="fit">
            <a href="{% url 'inventory:edit_item' item.id %}" class="btn btn-primary btn-sm">
                Edit
            </a>
          </td>
          <td class="fit">
            <a href="{% url 'inventory:notes' item.id %}" class="btn btn-info btn-sm">
                Notes
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</div>
<script>
  $(document).ready(function() {
      $('#inventoryTable').DataTable( {
          dom: 'Bfrtip',
          ordering: false,
          columnDefs: [
              {
                  targets: [0, 1, 10, 11, 12, 22, 23],
                  className: 'noVis'
              },
              {
                  "targets": [2, 16, 18, 19, 20, 21],
                  "visible": false

              }
          ],
          buttons: [
              'pageLength',
              {
                  extend: 'colvis',
                  columns: ':not(.noVis)'
              }
          ],
          orderCellsTop: true,
        initComplete: function() {
          var table = this.api();

        }
      } );
  } );
</script>
{% endblock %}

project/templates/inventory/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>


    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'inventory/styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <!-- HTMX -->
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>

    <!-- ColVis -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.colVis.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.ico' %}">

  <title>
    {% block title %} Home {% endblock %}
  </title>

  </head>

  <body>
    <!-- Page Content -->
    <div class="container-fluid">
        <div id="loader">
          <img
              class="loader-img"
              src="{% static 'images/Spinner-5.gif' %}"
              alt="Spinner..."
          />
      </div>
      <br />
      {% include "inventory/includes/_navbar.html" %} <!-- Navbar -->
      {% include "inventory/includes/_messages.html" %} <!-- Messages -->
      {% block body %}
      {% endblock %}
    </div>
    <!-- End container class-->

    <script type="text/JavaScript">
      setTimeout(function () {

        // Closing the alert
        $('.alert').hide(500);
      }, 7500);
    </script>

    <script type="text/JavaScript">
      window.addEventListener("load", () => {
        const loader = document.querySelector("#loader");
        loader.classList.add("hidden");
      })
    </script>
  </body>
</html>

project/templates/inventory/login_inventory.html
{% extends 'inventory/layout.html' %}
{% load crispy_forms_tags %}
{% block body %}
{% load static %}
 <div class="container-fluid"> 
 <header class="page-heading">
   <h1>Inventory Login</h1>
 </header>
 <hr>
  <form method="POST">
            {% csrf_token %}
            <div class="form-group"></div>
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" required=true>
            <div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" required=true>
            </div>
            <button class="btn btn-sm btn-primary" type="submit">Login</button>
        </form>
 </div>
{% endblock %}

project/templates/inventory/maintenance.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="#">
    <title>Site Maintenance</title>

    <style>
      body { text-align: center; padding: 150px;}
      h1 { font-size: 50px; color: red;}
      body { font: 24px Helvetica, sans-serif; color: #333; }
      article { display: block; text-align: left; width: 650px; margin: 0 auto; }
    </style>
</head>
<body>
<article>
        <h1>We&rsquo;ll be back soon!</h1>
        <div>
            <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. We&rsquo;ll be back online shortly!</p>
            <p style="font-weight: bold;">&mdash; System Administrator</p>
        </div>
    </article>

</body>
</html>

project/templates/inventory/notes.html
{% extends 'inventory/layout.html' %}
{% load static %}
{% block title %}Item Notes{% endblock %}
{% block body %}
<div class="page-content">
  <div class="container-fluid">
    <legend class="border-bottom mb-4">
      {{item}} Note(s)
    </legend>
      <div class="noteForm">
        <form class="form" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <div class="row">
              <div class="col-sm-12">
                <label for="comment">New Note</label>
                <textarea class="form-control form-control-sm" id="comment" name="comment" placeholder="Enter Note" required="true" rows="3"></textarea>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row" id="btn-row">
                <div class="col-sm-2">
                    <button
                      class="btn btn-success btn-sm"
                      id="submit"
                    >
                      Add
                    </button>
                    <a
                      href="{% url 'inventory:inventory'%}"
                      class="btn btn-secondary btn-sm"
                      type="submit"
                      >
                          Return to List
                    </a>
                </div>
            </div>
          </div>
      </form>
    </div>
    <br />
    <br />
    <table id="notesTable" class="table table-sm table-hover table-responsive-sm table-bordered" width="100%">
      <thead class="table-primary">
      <tr>
        <th class="fit">ID</th>
        <th class="fit">Comment</th>
        <th class="fit">Inserted By</th>
        <th class="fit">Inserted Date</th>
      </tr>
    </thead>
    <tbody>
      {% for note in item_notes %}
        <tr>
          <td class="fit">{{note.id}}</td>
          <td width="25%" style="text-align: left; word-wrap: break-all;">{{note.comment}}</td>
          <td class="fit" style="text-align: left;">{{note.inserted_by}}</td>
          <td class="fit">{{note.inserted_date|date:"m-d-Y h:i:s A"}}</td>
        </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>
</div>
<script>
  $(document).ready(function() {
      $('#notesTable').DataTable( {
          dom: 'Bfrtip',
          order: [[3, 'desc']],
          columnDefs: [
              {
                  targets: [0],
                  className: 'noVis'
              },
              {
                  "targets": [1, 2, 3],
                  "visible": true

              }
          ],
          buttons: [
              'pageLength',
              {
                  extend: 'colvis',
                  columns: ':not(.noVis)'
              }
          ],
          orderCellsTop: true,
        initComplete: function() {
          var table = this.api();

        }
      } );
  } );
</script>
{% endblock %}

project/templates/inventory/summary.html
{% extends 'inventory/layout.html' %}
{% load static %}
{% block title %}Summary{% endblock %}
{%block body %}
<div class="page-content">
    <div class="container">
        <main>
            <legend class="border-bottom mb4">
                Inventory Summary
            </legend>
            {% if msg %}
                <p class="no_records">{{msg}}</p>
            {% else %}
                {% autoescape off %}
                    {{ grouped_df|safe }}
                {% endautoescape %}
                <!-- {% autoescape off %}
                    {{ plt_div_bar }}
                {% endautoescape %} -->
                <br>
                <br>
                {% autoescape off %}
                    {{ plt_div_pie }}
                {% endautoescape %}
            {% endif %}
        </main>
    </div>
</div>
{% endblock %}