project/inventory/urls.py
from django.urls import path, reverse_lazy
from . import views


app_name = "inventory"

urlpatterns = [
    path("", views.index, name="index"),
    path("inventory/summary", views.summary, name="summary"),
    path("inventory/inventory", views.inventory, name="inventory"),
    path("inventory/add_item", views.add_item, name="add_item"),
    path("inventory/edit_item/<int:id>", views.edit_item, name="edit_item"),
    path("inventory/load_areas", views.load_areas, name="load_areas"),
    path("inventory/notes/<int:id>", views.notes, name="notes"),
    path(
        "inventory/export_to_excel", views.export_to_excel, name="export_to_excel"
    ),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path('maintenance/', views.maintenance, name='maintenance'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('autos/',  include('automotive.urls')),
    path('residential/',  include('residential.urls')),
    path('expense_tracking/',  include('expense_tracking.urls')),
    path('inventory/',  include('inventory.urls')),
]

project/inventory/models.py
from django.db import models
from django.utils import timezone


class MapLocation(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Map_Locations"

    def __str__(self):
        return self.name


class Area(models.Model):
    name = models.CharField(max_length=100)
    map_loc = models.ForeignKey(
        MapLocation,
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name_plural = "Areas"

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Manufacturers"

    def __str__(self):
        return self.name


class ApprovalList(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Approval_List"

    def __str__(self):
        return self.name


class Assignee(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Assignees"

    def __str__(self):
        return self.name


class ItemStatus(models.Model):
    name = models.CharField(max_length=250)

    class Meta:
        verbose_name_plural = "Item_Status"

    def __str__(self):
        return self.name


class InventoryItem(models.Model):
    asset_id = models.CharField(
        max_length=100,
        blank=True
    )
    name = models.CharField(max_length=100)
    stat = models.ForeignKey(
        ItemStatus,
        on_delete=models.CASCADE
    )
    description = models.TextField()
    item_location = models.ForeignKey(
        MapLocation,
        on_delete=models.CASCADE
    )
    item_area = models.ForeignKey(
        Area,
        on_delete=models.CASCADE
    )
    mfg = models.ForeignKey(
        Manufacturer,
        on_delete=models.CASCADE
    )
    model_no = models.CharField(max_length=100)
    serial_no = models.CharField(max_length=100, blank=True, null=True)
    qty = models.IntegerField()
    total_cost = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    cost_per_item = models.DecimalField(
        max_digits=8, decimal_places=2, blank=True, null=True
    )
    assigned_to = models.ForeignKey(
        Assignee,
        on_delete=models.CASCADE,
        blank=True,
        null=True
    )
    approved_by = models.ForeignKey(
        ApprovalList,
        on_delete=models.CASCADE
    )
    approved_date = models.DateField()
    purchased_from = models.CharField(max_length=100, blank=True)
    purchase_date = models.DateField()
    inserted_by = models.CharField(blank=True, null=True)
    inserted_date = models.DateField()
    modified_by = models.CharField(max_length=150, blank=True, null=True)
    modified_date = models.DateField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "Inventory_Items"

    def __str__(self):
        return self.name


class ItemNotes(models.Model):
    item = models.ForeignKey(
        InventoryItem,
        on_delete=models.CASCADE
    )
    comment = models.TextField()
    inserted_by = models.CharField(max_length=250)
    inserted_date = models.DateTimeField(
        default=timezone.now
    )

    class Meta:
        verbose_name_plural = "Item_Notes"

    def __str__(self):
        return self.item.name

project/inventory/forms.py
from django import forms
from .models import ItemNotes, InventoryItem


class InventoryForm(forms.ModelForm):

    class Meta:
        model = InventoryItem
        fields = (
            'asset_id',
            'name',
            'stat',
            'description',
            'item_location',
            'item_area',
            'mfg',
            'model_no',
            'serial_no',
            'qty',
            'total_cost',
            'cost_per_item',
            'assigned_to',
            'approved_by',
            'approved_date',
            'purchased_from',
            'purchase_date'
        )


class NoteForm(forms.ModelForm):

    class Meta:
        model = ItemNotes
        fields = (
            'comment',
        )

project/inventory/views.py
import logging
import csv
import datetime
import pandas as pd
import plotly.graph_objs as go

from pytz import timezone
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import (
    login, logout, authenticate, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import (
    InventoryItem,
    ItemNotes,
    ItemStatus,
    Area,
    MapLocation,
    Manufacturer,
    Assignee,
    ApprovalList
)
from .forms import (
    NoteForm,
    InventoryForm
)
from django.urls import reverse_lazy
from plotly.offline import plot
from pretty_html_table import build_table


logger = logging.getLogger(__name__)
EST = timezone('US/Eastern')


def maintenance(request):
    return render(
        request=request,
        template_name='inventory/maintenance.html')


def index(request):
    return render(request=request,
                  template_name="inventory/index.html"
                  )


@login_required
def summary(request):

    try:
        # Create dataframe from all records for specified fields
        df = pd.DataFrame(list(
            InventoryItem.objects.all().values(
                'item_location__name',
                'qty',
                'total_cost'
            )
        )
        )

        if len(df.index) == 0:
            return render(
                request=request,
                template_name='inventory/summary.html',
                context={
                    'msg': 'No records found!'
                }
            )
        else:
            #grouped_df = df.groupby(
            #    'item_location__name', as_index=False
            #    ).sum()

            grouped_df = df.groupby(
                ['item_location__name']
                ).agg({'qty': 'sum', 'total_cost': 'sum'}).reset_index()

            grouped_df.columns = [
                'Location', 'Total Number of Items', 'Total Cost'
            ]

            #grouped_df['Total Cost'] = grouped_df['Total Cost'].map(
            #    '${:,.2f}'.format)

            if len(grouped_df.index) == 0:
                return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'msg': 'No records found!'
                    }
                )
            else:

                trace_pie = go.Pie(
                    values=grouped_df['Total Number of Items'],
                    labels=grouped_df['Location'],
                    # textinfo='percent+value',
                )

                config = {
                    'responsive': True,
                    'displaylogo': False
                }

                data = [trace_pie]

                fig_pie = go.Figure(data=data)

                fig_pie.update_layout(
                    autosize=True,
                    # width=600,
                    # height=600,
                    title_text='<b>Inventory Percentage per Location</b>',
                    title_x=0.50,
                    title_y=0.95,
                    title_font=dict(size=18),
                    legend_font_size=14,
                    legend=dict(
                        orientation="h"
                    ),
                    # legend_yanchor='bottom',
                    # legend_y=0,
                    # legend_xanchor='right',
                    # legend_x=2.5,
                    # margin=dict(
                    #     l=0,
                    #     r=0,
                    #     b=0,
                    #     t=0
                    # ),
                )

                plt_div_pie = plot(
                    fig_pie, config=config, output_type='div'
                )

                return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'grouped_df': build_table(
                            grouped_df,
                            'blue_dark',
                            text_align='right'
                        ),
                        'plt_div_pie': plt_div_pie
                    }
                )

    except Exception as e:
        logging.error(f'Exception on data visualization: {e}')
        return render(
                    request=request,
                    template_name='inventory/summary.html',
                    context={
                        'msg': 'No records found!'
                    }
                )

@login_required
def inventory(request):
    #inventory_list = InventoryItem.objects.all()
    inventory_list = InventoryItem.objects.all().values(
        'id',
        'asset_id',
        'name',
        'stat__name',
        'description',
        'item_location__name',
        'item_area__name',
        'mfg__name',
        'model_no',
        'serial_no',
        'qty',
        'total_cost',
        'cost_per_item',
        'assigned_to__name',
        'approved_by__name',
        'approved_date',
        'purchased_from',
        'purchase_date',
        'inserted_by',
        'inserted_date',
        'modified_by',
        'modified_date'
    ).order_by('-purchase_date')

    return render(request=request,
                  template_name="inventory/inventory.html",
                  context={
                      'inventory_list': inventory_list
                  }
                  )


@login_required
def load_areas(request):
    loc = request.GET.get('item_location')
    areas = Area.objects.filter(map_loc=loc).order_by('name')
    return render(
        request=request,
        template_name="inventory/areasOpts.html",
        context={
            'loc': loc,
            'areas': areas
        }
    )


@login_required
def add_item(request):
    stats = ItemStatus.objects.all().values().order_by('name').values()
    areas = Area.objects.all().values().order_by('name').values()
    locations = MapLocation.objects.all().values().order_by('name').values()
    mfgs = Manufacturer.objects.all().order_by('name').values()
    assignees = Assignee.objects.all().order_by('name').values()
    approvers = ApprovalList.objects.all().order_by('name').values()

    if request.method == "POST":
        form = InventoryForm(request.POST)

        if form.is_valid():

            item_to_insert = form.save(commit=False)
            item_to_insert.stat = form.cleaned_data['stat']
            item_to_insert.asset_id = form.cleaned_data['asset_id']
            item_to_insert.name = form.cleaned_data['name']
            item_to_insert.description = form.cleaned_data['description']
            item_to_insert.item_location = form.cleaned_data['item_location']
            item_to_insert.item_area = form.cleaned_data['item_area']
            item_to_insert.mfg = form.cleaned_data['mfg']
            item_to_insert.model_no = form.cleaned_data['model_no'].upper()
            if form.cleaned_data['serial_no'] is None:
                item_to_insert.serial_no = form.cleaned_data['serial_no']
            else:
                item_to_insert.serial_no = (
                    form.cleaned_data['serial_no'].upper())
            item_to_insert.qty = form.cleaned_data['qty']
            item_to_insert.total_cost = form.cleaned_data['total_cost']
            item_to_insert.cost_per_item = form.cleaned_data['total_cost']/form.cleaned_data['qty']
            item_to_insert.assigned_to = form.cleaned_data['assigned_to']
            item_to_insert.approved_by = form.cleaned_data['approved_by']
            item_to_insert.approved_date = form.cleaned_data['approved_date']
            item_to_insert.purchased_from = form.cleaned_data['purchased_from']
            item_to_insert.purchase_date = form.cleaned_data['purchase_date']
            item_to_insert.inserted_by = request.user
            item_to_insert.inserted_date = datetime.datetime.now(tz=EST)
            item_to_insert.save()
            messages.success(
                request,
                'New inventory item added successfully!'
            )

            return redirect('inventory:inventory')

        else:
            return render(
                request=request,
                template_name="inventory/add_item.html",
                context={"form": form}
            )

    else:
        form = NoteForm()
        return render(
            request=request,
            template_name="inventory/add_item.html",
            context={
                'stats': stats,
                'areas': areas,
                'locations': locations,
                'mfgs': mfgs,
                'assignees': assignees,
                'approvers': approvers
            }
        )


@login_required
def edit_item(request, id):

    # Obtain record to edit by id
    entry_to_edit = InventoryItem.objects.get(id=id)

    # Obtain list of status in order by name, except the selected value
    # by id from the form
    stat_list = ItemStatus.objects.exclude(
        id=entry_to_edit.stat.pk
    ).order_by('name')

    # Obtain list of locations in order by name, except the selected value
    # by id from the form
    loc_list = MapLocation.objects.exclude(
        id=entry_to_edit.item_location.pk
    ).order_by('name')

    # Get area
    # current_area = entry_to_edit.location.name
    # lst = (list(current_area.split(" ")))
    # cur_area = lst[0]

    # Obtain list of areas in order by name, except the selected value
    # by id from the form
    area_list = Area.objects.filter(
        map_loc=entry_to_edit.item_location.pk).order_by('name')

    # Obtain list of manufacturers in order by name, except the selected value
    # by id from the form
    mfg_list = Manufacturer.objects.exclude(
        id=entry_to_edit.mfg.pk
    ).order_by('name')

    # Obtain list of assignees in order by name, except the selected value

project/templates/inventory/includes/_form_errors.html
{% if form.errors %}
    <ul class="errorlist">
        {% for field in form %}
            {% for error in field.errors %}
                <li>
                    {{ field.label }}:  {{ error|escape }}
                </li>
            {% endfor %}
        {% endfor %}
    </ul>
{% endif %}

{% if form.non_field_errors %}
    <ul class="errorlist">
        {% for err in form.non_field_errors %}
            <li>
              {{ err }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

{% if form.old_password.errors %}
    <ul class="errorlist">
        {% for oldpass_err in form.old_password.errors %}
              <li>
                  {{ oldpass_err }}
              </li>
        {% endfor %}
    </ul>
{% endif %}

{% if form.new_password2.errors %}
    <ul class="errorlist">
        {% for newpass_err in form.new_password2.errors %}
            <li>
                {{ newpass_err }}
            </li>
        {% endfor %}
    </ul>
{% endif %}

project/templates/inventory/includes/_messages.html
{% if messages %}
    {% for message in messages%}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
            <div class="alert alert-primary alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div class="alert alert-success alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-warning alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger alert-dismissable" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></span></button>
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

project/templates/inventory/includes/_navbar.html
<!-- Navigation -->
{% load static %}
<nav
class="navbar navbar-expand-lg navbar-dark fixed-top"
style="background-color: #1432b4"
>
<div class="container-fluid">
<a class="navbar-brand" href="{% url 'inventory:index' %}">Home Inventory</a>
<button
  class="navbar-toggler"
  type="button"
  data-toggle="collapse"
  data-target="#navbarResponsive"
  aria-controls="navbarResponsive"
  aria-expanded="false"
  aria-label="Toggle navigation"
>
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav ml-auto">
    {% if user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Inventory
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'inventory:summary' %}">Summary</a>
          <a class="dropdown-item" href="{% url 'inventory:inventory' %}">View List</a>
          <a class="dropdown-item" href="{% url 'inventory:add_item' %}">Add Item</a>
          <a class="dropdown-item" href="{% url 'inventory:export_to_excel' %}">Export to Excel</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inventory:logout_request' %}">Logout</a>
      </li>
      <li>
        <a class="nav-link disabled" href="#">Logged in as {{ user.username }}</a>
      </li>
    {% else %}
      <li>
        <a class="nav-link" href="{% url 'inventory:index' %}"
          >Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inventory:login_request' %}">Login</a>
      </li>
    {% endif %}
  </ul>
</div>
</div>
</nav>