project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('autos/',  include('automotive.urls')),
    path('residential/',  include('residential.urls')),
    path('expense_tracking/',  include('expense_tracking.urls')),
    path('inventory/',  include('inventory.urls')),
]

project/residential/urls.py
from django.urls import path
from . import views


app_name = "residential"

urlpatterns = [
    path('', views.index, name="index"),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path("accounts/login/", views.login_request, name="login_request"),
    path('task_log/', views.task_log, name="task_log"),
    path('add_task/', views.add_task, name="add_task"),
    path(
        'task_log/edit_task/<int:id>/',
        views.edit_task,
        name="edit_task"
    ),
    path('export_to_excel/', views.export_to_excel, name="export_to_excel"),
    path('filter/<int:id>', views.filter, name="filter"),
]

project/residential/models.py
from django.db import models


class Vendor(models.Model):
    """
    Model defines a vendor which has name, address, city
    state, postal code and office number.
    """
    name = models.TextField()
    address = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50, blank=True)
    vendor_state = models.CharField(max_length=2, blank=True)
    postal_code = models.CharField(max_length=8, blank=True)
    office_number = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=255, blank=True)
    website = models.TextField(blank=True)

    def __str__(self):
        """
        Represent vendor class object as a string consisting of the
        vendor's name.
        """
        return self.name


class Task(models.Model):
    """
    Model defines a task performed by a vendor which has
    task_date, name, vendor, vendor_rep, contact_num, documentation,
    cost and notes.
    """
    task_date = models.DateField()
    name = models.CharField(max_length=60)
    vendor = models.ForeignKey(
        Vendor,
        blank=True,
        on_delete=models.CASCADE
    )
    vendor_rep = models.CharField(max_length=50, blank=True)
    contact_num = models.CharField(max_length=10, blank=True)
    documentation = models.TextField(blank=True)
    cost = models.DecimalField(blank=True, max_digits=8, decimal_places=2)
    notes = models.TextField(blank=True)

    def __str__(self):
        """
        Represent task class object as a string consisting of the
        task's name.
        """
        return self.name

project/residential/forms.py
from django import forms
from .models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'task_date',
            'name',
            'vendor',
            'vendor_rep',
            'contact_num',
            'documentation',
            'cost',
            'notes',
        ]

    def clean_vendor(self):
        vendor = self.cleaned_data.get('vendor')
        if vendor is None:
            raise forms.ValidationError(
                'Please select a vendor from the dropdown!'
            )
        return vendor

    def save(self, commit=True):
        task = super(TaskForm, self).save(commit=False)
        task_date = self.cleaned_data['task_date']
        name = self.cleaned_data['name']
        vendor = self.cleaned_data['vendor']
        vendor_rep = self.cleaned_data['vendor_rep']
        contact_num = self.cleaned_data['contact_num']
        documentation = self.cleaned_data['documentation']
        cost = self.cleaned_data['cost']
        notes = self.cleaned_data['notes']
        if commit:
            task.save()
            return task

project/residential/views.py
import datetime
import logging

from django.shortcuts import render, redirect
from .models import Task, Vendor
from .forms import TaskForm
from django.contrib import messages
from django.core.paginator import Paginator
from excel_response import ExcelResponse
from django.contrib.auth.models import User
from django.contrib.auth import (
    login, logout, authenticate, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
# from .signals import log_user_logout
from django.contrib.auth.forms import AuthenticationForm
from .signals import log_user_logout
from django.contrib.auth.views import logout_then_login


logger = logging.getLogger('residential')


def index(request):
    return render(
        request=request,
        template_name="residential/index.html"
    )


def login_request(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(
                    request,
                    f'{username} logged in successfully.'
                )
                logger.info(f'{request.user} logged in successfully.')
                return redirect("residential:task_log")

            elif User.objects.filter(
                    username=form.cleaned_data.get('username')).exists():
                user = User.objects.filter(
                    username=form.cleaned_data.get('username')).values()
                if(user[0]['is_active'] is False):
                    messages.info(
                        request,
                        "Contact the administrator to activate your account!"
                    )
                    return redirect("residential:login_request")

                else:
                    messages.error(request, 'Something went wrong!')
                    return render(
                        request=request,
                        template_name="residential/login_residential.html",
                        context={"form": form}
                    )

            else:
                messages.error(request, 'Something went wrong!')
                return render(
                    request=request,
                    template_name="residential/login_residential.html",
                    context={"form": form}
                )
        else:
            form = AuthenticationForm()
            return render(
                request=request,
                template_name="residential/login_residential.html",
                context={"form": form}
            )
    else:
        messages.info(
            request,
            '''You are already logged in.  You must log out to log in as
            another user.'''
        )
        return redirect("residential:index")


@login_required
def add_task(request):

    vendors = Vendor.objects.order_by('name')

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Task saved successfully!')
            return redirect('residential:task_log')

        else:
            return render(
                request=request,
                template_name='residential/add_task.html',
                context={
                    'form': form,
                    'vendors': vendors
                }
            )

    else:
        form = TaskForm()

    return render(
        request=request,
        template_name='residential/add_task.html',
        context={
            'form': form,
            'vendors': vendors
        }
    )


@login_required
def edit_task(request, id):
    task = Task.objects.get(id=id)

    vendors = Vendor.objects.exclude(
        id=task.pk).order_by('name')

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Your task record was updted successfully!'
            )
            return redirect('residential:task_log')

    else:
        form = TaskForm(instance=task)

        return render(
            request=request,
            template_name='residential/edit_task.html',
            context={
                'form': form,
                'task': task,
                'vendors': vendors
            }
        )


@login_required
def task_log(request):
    # Set up pagination
    p = Paginator(Task.objects.order_by('-task_date'), 10)
    page = request.GET.get('page')
    tasks = p.get_page(page)

    vendors = Vendor.objects.order_by('name')

    return render(
        request=request,
        template_name="residential/task_log.html",
        context={
            'tasks': tasks,
            'vendors': vendors
        }
    )


@login_required
def filter(request, id):
    # Set up pagination
    p = Paginator(Task.objects.filter(vendor=id).order_by('-task_date'), 10)
    page = request.GET.get('page')
    tasks = p.get_page(page)

    vendors = Vendor.objects.order_by('name')

    return render(
        request=request,
        template_name="residential/task_log.html",
        context={
            'tasks': tasks,
            'vendors': vendors
        }
    )


@login_required
def export_to_excel(request):
    tasks = Task.objects.all().values(
        'id',
        'task_date',
        'name',
        'vendor__name',
        'vendor_rep',
        'contact_num',
        'documentation',
        'cost',
        'notes'
    )

    file_date_str = datetime.datetime.now().strftime('%Y%m%d')
    return ExcelResponse(
        data=tasks,
        output_filename=f'tasks_{file_date_str}',
        worksheet_name="tasks"
    )


@login_required
def logout_request(request):
    logout(request)
    logger.info('You were successfully logged out.')
    return redirect('residential:index')

project/templates/residential/add_task.html
{% extends 'residential/residential_base.html' %}
{% block title %}Add Task{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <header class="page-heading">
        <h1>Add Task</h1>
    </header>
    <hr>
    <form class="form" method="POST">
        {%csrf_token%}
        <div class="form-group">
            <div class="row">
                <div class="col-sm-3">
                    <label for="task_date">Task Date:</label>
                    <input
                        type="date"
                        class="form-control form-control-sm"
                        data-date-format="mm/dd/yyyy"
                        id="task_date"
                        name="task_date"
                        required="true"
                    />
                </div>
                <div class="col-sm-9">
                    <label for="documentation">Documentation Link:</label>
                    <input
                        class="form-control form-control-sm"
                        type="text"
                        id="documentation"
                        name="documentation"
                    />
                </div>
            </div> <!-- end row -->
            <div class="row">
                <div class="col-sm-6">
                    <label for="vendor">Vendor</label>
                    <select
                        class="form-control form-control-sm"
                        id="vendor"
                        name="vendor"
                        required="true"
                    />
                        <option
                        selected="true"
                        value="Select a Vendor"
                        disabled
                        >
                            Select a Vendor
                        </option>
                        {% for vendor in vendors %}
                        <option value="{{ vendor.id}}">
                            {{ vendor.name }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-6">
                        <label for="name">Task Name:</label>
                        <input
                            class="form-control form-control-sm"
                            id="name"
                            name="name"
                        />
                </div>
            </div>  <!-- end row -->
            {% if form.vendor.errors or form.name.errors %}
            <div class="row">
                <div class="col-sm-6 err">
                    {% for error in form.vendor.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
                <div class="col-sm-6 err">
                    {% for error in form.name.errors %}
                        {{ error|escape }}
                    {% endfor %}
                </div>
            </div>  <!-- end row -->
            {% endif %}
            <div class="row">
                <div class="col-sm-4">
                        <label for="vendor_rep">Vendor Rep:</label>
                        <input
                            class="form-control form-control-sm"
                            id="vendor_rep"
                            name="vendor_rep"
                        />
                </div>
                <div class="col-sm-4">
                        <label for="contact_num">Contact Number:</label>
                        <input
                            type="text"
                            class="form-control form-control-sm"
                            id="contact_num"
                            name="contact_num"
                        />
                </div>
                <div class="col-sm-4">
                        <label for="cost">Cost:</label>
                        <div class="input-group-append input-group-sm">
                            <span class="form-control-sm input-group-text input-group-sm">$</span>
                        <input
                            type="number"
                            class="form-control form-control-sm"
                            id="cost"
                            name="cost"
                            required="true"
                            step=".01"
                            value="0"
                        />
                    </div>
                </div>
            </div>  <!-- end row -->
                <div class="row">
                <div class="col-sm-12">
                    <label for="notes">Notes:</label>
                    <textarea
                        class="form-control form-control-sm textarea"
                        id="notes"
                        name="notes"
                        row="10"
                    />
                    </textarea>
                </div>
            </div> <!-- end row -->
        </div> <!-- end form group -->
        <br>
        <div class="form-group">
            <button
                class="btn btn-sm btn-primary"
                id="add_task_btn"
                type="submit"
                >
                    Submit
            </button>
            <button
                class="btn btn-sm btn-secondary"
                onclick="javascript:history.back()"
            >
                Cancel
            </button>
        </div>
    </form>
</div>
{% endblock %}

project/templates/residential/edit_task.html
{% extends 'residential/residential_base.html' %}
{% block title %}Edit Task{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <header class="page-heading">
        <h1>Edit Task</h1>
    </header>
    <hr>
    <form class="form" method="POST">
        {%csrf_token%}
        <div class="form-group">
            <div class="row">
                <div class="col-sm-3">
                    <label for="task_date">Task Date:</label>
                    {% if task %}
                    <input
                        type="date"
                        class="form-control form-control-sm"
                        id="task_date"
                        name="task_date"
                        required="true"
                        value='{{task.task_date|date:"Y-m-d"}}'
                    />
                    {% endif %}
                </div>
                <div class="col-sm-9">
                    <label for="documentation">Documentation Link:</label>
                    <input
                        class="form-control form-control-sm"
                        type="text"
                        id="documentation"
                        name="documentation"
                        value"{{ task.documentation }}"
                    />
                </div>
            </div> <!-- end row -->
            <div class="row">
                <div class="col-sm-6">
                    {% if task %}
                    <label for="vendor">Vendor</label>
                    <select
                        class="form-control form-control-sm"
                        id="vendor"
                        name="vendor"
                        required="true"
                    />
                        <option
                        selected="true"
                        value="{{ task.vendor.pk}}"
                        >
                            {{ task.vendor }}
                        </option>
                        {% for vendor in vendors %}
                        <option value="{{ vendor.id}}">
                            {{ vendor.name }}
                            </option>
                        {% endfor %}
                    </select>
                    {% endif %}
                </div>
                <div class="col-sm-6">
                    {% if task %}
                        <label for="name">Task Name:</label>
                        <input
                            class="form-control form-control-sm"
                            id="name"
                            name="name"
                            required="true"
                            value="{{ task.name }}"
                        />
                    {% endif %}
                </div>
            </div>  <!-- end row -->
            <div class="row">
                <div class="col-sm-4">
                    {% if task %}
                        <label for="vendor_rep">Vendor Rep:</label>
                        <input
                            class="form-control form-control-sm"
                            id="vendor_rep"
                            name="vendor_rep"
                            value="{{ task.vendor_rep}}"
                        />
                    {% endif %}
                </div>
                <div class="col-sm-4">
                    {% if task %}
                        <label for="contact_num">Contact Number:</label>
                        <input
                            type="text"
                            class="form-control form-control-sm"
                            id="contact_num"
                            name="contact_num"
                            value="{{ task.contact_num }}"
                        />
                    {% endif %}
                </div>
                <div class="col-sm-4">
                    {% if task %}
                        <label for="cost">Cost:</label>
                        <div class="input-group-append input-group-sm">
                            <span class="form-control-sm input-group-text input-group-sm">$</span>
                        <input
                            type="number"
                            class="form-control form-control-sm"
                            id="cost"
                            name="cost"
                            required="true"
                            step=".01"
                            value="{{ task.cost }}"
                        />
                    </div>
                    {% endif %}
                </div>
            </div>  <!-- end row -->
                <div class="row">
                <div class="col-sm-12">
                    <label for="notes">Notes:</label>
                    {% if task %}
                    <textarea
                        class="form-control form-control-sm textarea"
                        id="notes"
                        name="notes"
                        row="10"
                    />
                        {{ task.notes }}
                    </textarea>
                    {% endif %}
                </div>
            </div> <!-- end row -->
        </div> <!-- end form group -->
        <br>
        <div class="form-group">
            <button
                class="btn btn-sm btn-primary"
                id="add_task_btn"
                type="submit"
                >
                    Submit
            </button>
            <button
                class="btn btn-sm btn-secondary"
                onclick="javascript:history.back()"
            >
                Cancel
            </button>
        </div>
    </form>
</div>
{% endblock %}

project/templates/residential/index.html
{% extends 'residential/residential_base.html' %}
{% block title %}Residential Home{% endblock %}
{% block body %}
{% load static %}
<div>
    <main role="main">
            <header class="page-heading">
                <h1>Residential Home</h1>
            </header>
            <section class="page-content">
                    <div class="grid-container">
                        <div id="longleaf">
                            <img
                            src="{% static  'residential/img/HomeImage.jpg' %}"
                            alt="Image of house"
                            class="responsive"
                            />
                        </div>
                    </div>
            </section>
        </main>
</div>
{% endblock %}

project/templates/residential/login_residential.html
{% extends 'residential/residential_base.html' %}
{% load crispy_forms_tags %}
{% block body %}
{% load static %}
 <div class="container-fluid"> 
 <header class="page-heading">
   <h1>Residential Login</h1>
 </header>
 <hr>
    <form method="POST">
            {% csrf_token %}
            <div class="form-group"></div>
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" required=true>
            <div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" required=true>
            </div>
            <button class="btn btn-sm btn-primary" type="submit">Login</button>
        </form>
 </div>
{% endblock %}

project/templates/residential/residential_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'automotive/img/favicon.ico' %}" >
    <link rel="stylesheet" href="{% static 'residential/css/styles.css' %}">

  <title>
    {% block title %} Base {% endblock %}
  </title>
  </head>

  <body>
    <div class="container-fluid"> <!-- container-fluid class-->

      <!-- Page Content -->
      {% include 'residential/includes/_navbar.html' %}
      {% include 'residential/includes/_messages.html' %}
      {% include 'residential/includes/_form_errors.html' %}
      {% block body %}
      {% endblock %}<!-- End Page Content -->

    </div> <!-- End container-fluid class-->

    <script type="text/Javascript">
      setTimeout(function() {
        //Closing the alert
        $('.alert').alert('close');
    }, 3000);
    </script>

  </body>
</html>

project/templates/residential/task_log.html
{% extends 'residential/residential_base.html' %}
{% block title %}Residential Log{% endblock %}
{% block body %}
{% load static %}
    <div class="container-fluid">
      <header class="page-heading">
          <h1>Residential Log</h1>
      </header>
      <hr>
      <div class="row">
          <div class="col-sm-3">
              <a href="{% url 'residential:export_to_excel' %}" class="btn btn-dark btn-sm">
                  Export Full Log to Excel
              </a>
          </div>
      </div>
      <hr>
      <form>
          <div class="form-group row">
              <label for="vendor"class="col-sm-2 col-form-label">Filter by Vendor</label>
              <div class="col-sm-3 select-update">
                  <select
                      class="form-control form-control-sm"
                      id="vendor"
                      name="vendor"
                      onchange="location = this.value;"
                  >
                      <option
                      selected="true"
                      value="Select a Vendor"
                      disabled
                      >
                          Select a Vendor
                      </option>
                      <option value="{% url 'residential:task_log' %}">
                          All Vendors
                      </option>
                      {% for vendor in vendors %}
                      <option value="{% url 'residential:filter'  vendor.id %}">
                            {{vendor.name}}
                      </option>
                      {% endfor %}
                  </select>
              </div>
            </div>
        </form>
        <table class="table table-striped table-responsive-sm table-bordered">
        	<tr>
        		<th class="fit">ID</th>
    			<th class="fit">Task Date</th>
        		<th class="fit">Task Name</th>
        		<th class="fit">Vendor</th>
        		<th class="fit">Vendor Rep</th>
        		<th class="fit">Contact Number</th>
        		<th class="fit">Documentation</th>
    			<th class="fit">Cost</th>
    			<th class="fit">Notes</th>
                <th class="fit">Edit</th>
        	</tr>
        	{% for task in tasks %}
        		<tr>
        			<td class="fit">{{task.id}}</td>
    				<td class="fit">{{task.task_date}}</td>
            			<td class="fit">{{task.name}}</td>
            			<td class="fit">{{task.vendor}}</td>
            			<td class="fit">{{task.vendor_rep}}</td>
            			<td class="fit">{{task.contact_num}}</td>
                        {% if task.documentation %}
        				    <td class="fit">
                                <a href="{{task.documentation}}" target="_blank">
                                    View
                                </a>
                            </td>
                        {% else %}
                            <td class="fit">
                                <p>
                                    No File
                                </p>
                            </td>
                        {% endif %}
        				<td class="fit" id="task_cost">${{task.cost|floatformat:2}}</td>
        				<td class="fit">{{task.notes}}</td>
                        <td class="fit">
                            <a href="{% url 'residential:edit_task' task.id%}" class="btn btn-primary btn-sm">
                                Edit
                            </a>
                        </td>
        		</tr>
        	{% endfor %}
        </table>
        <br>
        <nav aria-label="Page navigation">
          <ul class="pagination  pagination-sm">

              {% if tasks.has_previous %}

                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        &laquo First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ tasks.previous_page_number }}">
                        Previous
                    </a>
                </li>

              {% endif %}

              <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                      Page {{ tasks.number }} of {{ tasks.paginator.num_pages }}
                  </a>
              </li>

              {% if tasks.has_next %}

                <li class="page-item">
                    <a class="page-link" href="?page={{ tasks.next_page_number }}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ tasks.paginator.num_pages }}">
                        Last &raquo
                    </a>
                </li>

              {% endif %}

          </ul>
        </nav>
    </div>
{% endblock %}