project/automotive/urls.py
from django.urls import path
from . import views


app_name = "automotive"

urlpatterns = [
    path('', views.index, name="index"),
    path("accounts/login/", views.login_request, name="login_request"),
    path("accounts/logout/", views.logout_request, name="logout_request"),
    path('log/', views.log, name="log"),
    path('add_service/', views.add_service, name="add_service"),
    path(
        'log/edit_service/<int:id>/',
        views.edit_service,
        name="edit_service"
    ),
    path('export_to_excel/', views.export_to_excel, name="export_to_excel"),
    path(
        'vehicle_filter/<int:id>',
        views.vehicle_filter,
        name="vehicle_filter"
    ),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('portfolio.urls')),
    path('admin/', admin.site.urls),
    path('autos/',  include('automotive.urls')),
    path('residential/',  include('residential.urls')),
    path('expense_tracking/',  include('expense_tracking.urls')),
    path('inventory/',  include('inventory.urls')),
]

project/automotive/models.py
from django.db import models


class Vehicle(models.Model):
    """
    Model defines a vehicle which has make, model, year
    vin, license_plate and color.
    """
    make = models.CharField(max_length=25)
    model = models.CharField(max_length=25)
    year = models.CharField(max_length=4)
    vin = models.CharField(max_length=17)
    license_plate = models.CharField(max_length=8)
    color = models.CharField(max_length=15)

    def __str__(self):
        """
        Represent vehicle class object as a string consisting of the
        year, make and model.
        """
        return self.year + ' ' + self.make + ' ' + self.model


class Dealership(models.Model):
    """
    Model defines a dealership which has name, address, city
    state, postal code and office number.
    """
    name = models.TextField()
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    dealership_state = models.CharField(max_length=2)
    postal_code = models.CharField(max_length=8)
    office_number = models.CharField(max_length=15)

    def __str__(self):
        """
        Represent dealership class object as a string consisting of the
        dealership name.
        """
        return self.name


class Advisor(models.Model):
    """
    Model defines a service advisor at a dealership which has name,
    address, city, state, postal code and office number.
    """
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=50)
    employee_number = models.CharField(max_length=25)
    email = models.EmailField(max_length=255)
    contact_number = models.CharField(max_length=15)
    dealership = models.ForeignKey(
        Dealership,
        blank=True,
        on_delete=models.CASCADE
    )

    def __str__(self):
        """
        Represent advisor class object as a string consisting of the
        advisor's first and last name.
        """
        return self.first_name + ' ' + self.last_name


class Service(models.Model):
    """
    Model defines a service performed at a dealership which has
    service_date, link, make, dealership, service, service_advisor,
    mileage, cost, comments and inserted_date.
    """
    service_date = models.DateField(blank=True)
    link = models.TextField(blank=True)
    make = models.ForeignKey(
        Vehicle,
        blank=True,
        on_delete=models.CASCADE
    )
    dealership = models.ForeignKey(
        Dealership,
        blank=True,
        on_delete=models.CASCADE
    )
    work_performed = models.TextField()
    service_advisor = models.ForeignKey(
        Advisor,
        blank=True,
        on_delete=models.CASCADE
    )
    mileage = models.IntegerField(blank=True)
    cost = models.DecimalField(blank=True, max_digits=8, decimal_places=2)
    comments = models.TextField(blank=True)
    inserted_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """
        Represent service class object as a string consisting of the
        service date and make.
        """
        return str(self.make) + '@' + str(self.mileage) + 'mi'

project/automotive/forms.py
from django import forms
from .models import Service
from datetime import datetime


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = [
            'service_date',
            'link',
            'make',
            'dealership',
            'work_performed',
            'service_advisor',
            'mileage',
            'cost',
            'comments',
        ]

        readonly_fields = [
            'inserted_date'
        ]

    def clean_make(self):
        make = self.cleaned_data.get('make')
        if make is None:
            raise forms.ValidationError(
                'Please select a make from the dropdown!'
            )
        return make

    def clean_dealership(self):
        dealership = self.cleaned_data.get('dealership')
        if dealership is None:
            raise forms.ValidationError(
                'Please select a dealership from the dropdown!'
            )
        return dealership

    def clean_service_advisor(self):
        service_advisor = self.cleaned_data.get('service_advisor')
        if service_advisor is None:
            raise forms.ValidationError(
                'Please select a service advisor from the dropdown!'
            )
        return service_advisor

    def save(self, commit=True):
        service = super(ServiceForm, self).save(commit=False)
        service_date = self.cleaned_data['service_date']
        link = self.cleaned_data['link']
        make = self.cleaned_data['make']
        dealership = self.cleaned_data['dealership']
        work_performed = self.cleaned_data['work_performed']
        service_advisor = self.cleaned_data['service_advisor']
        mileage = self.cleaned_data['mileage']
        cost = self.cleaned_data['cost']
        comments = self.cleaned_data['comments']
        inserted_date = datetime.now()
        if commit:
            service.save()
            return service

project/automotive/views.py
import datetime
import logging

from django.shortcuts import render, redirect
from .models import Service, Vehicle, Dealership, Advisor
from .forms import ServiceForm
from django.contrib import messages
from django.core.paginator import Paginator
from excel_response import ExcelResponse
from django.contrib.auth.models import User
from django.contrib.auth import (
      login, logout, authenticate, update_session_auth_hash
)
from django.contrib.auth.decorators import login_required
# from .signals import log_user_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import logout_then_login


logger = logging.getLogger(__name__)


def index(request):
    return render(
        request=request,
        template_name="automotive/index.html"
    )


def login_request(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(
                    request,
                    f'{username} logged in successfully.'
                )
                return redirect("automotive:log")

            elif User.objects.filter(
                    username=form.cleaned_data.get('username')).exists():
                user = User.objects.filter(
                    username=form.cleaned_data.get('username')).values()
                if(user[0]['is_active'] is False):
                    messages.info(
                        request,
                        "Contact the administrator to activate your account!"
                    )
                    return redirect("automotive:login_request")

                else:
                    messages.error(request, 'Something went wrong!')
                    return render(
                        request=request,
                        template_name="automotive/login_automotive.html",
                        context={"form": form}
                    )

            else:
                messages.error(request, 'Something went wrong!')
                return render(
                    request=request,
                    template_name="automotive/login_automotive.html",
                    context={"form": form}
                )
        else:
            form = AuthenticationForm()
            return render(
                request=request,
                template_name="automotive/login_automotive.html",
                context={"form": form}
            )
    else:
        messages.info(
            request,
            '''You are already logged in.  You must log out to log in as
            another user.'''
        )
        return redirect("automotive:index")


@login_required
def add_service(request):

    vehicles = Vehicle.objects.order_by('year', 'make')
    dealerships = Dealership.objects.order_by('name')
    advisors = Advisor.objects.order_by('last_name')

    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Service record saved successfully!')
            return redirect('automotive:log')

        else:
            return render(
                request=request,
                template_name='automotive/add_service.html',
                context={
                    'form': form
                }
            )

    else:
        form = ServiceForm()

    return render(
        request=request,
        template_name='automotive/add_service.html',
        context={
            'form': form,
            'vehicles': vehicles,
            'dealerships': dealerships,
            'advisors': advisors
        }
    )


@login_required
def edit_service(request, id):
    service = Service.objects.get(id=id)

    vehicles = Vehicle.objects.exclude(
        id=service.make.pk).order_by('year', 'make')
    dealerships = Dealership.objects.exclude(
        id=service.dealership.pk).order_by('name')
    advisors = Advisor.objects.exclude(
        id=service.service_advisor.pk).order_by('last_name')

    if request.method == 'POST':
        form = ServiceForm(request.POST, instance=service)

        if form.is_valid():
            form.save()
            messages.success(
                request,
                'Your service record was updted successfully!'
            )
            return redirect('automotive:log')

    else:
        form = ServiceForm(instance=service)

        return render(
            request=request,
            template_name='automotive/edit_service.html',
            context={
                'form': form,
                'service': service,
                'vehicles': vehicles,
                'dealerships': dealerships,
                'advisors': advisors
            }
        )


@login_required
def vehicle_filter(request, id):
    # Set up pagination
    p = Paginator(
        Service.objects.filter(make_id=id).order_by('-service_date'),
        10
    )
    page = request.GET.get('page')
    services = p.get_page(page)

    vehicles = Vehicle.objects.all()

    return render(
        request=request,
        template_name="automotive/log.html",
        context={
            'services': services,
            'vehicles': vehicles
        }
    )


@login_required
def log(request):
    # Set up pagination
    p = Paginator(Service.objects.order_by('-service_date'), 10)
    page = request.GET.get('page')
    services = p.get_page(page)

    vehicles = Vehicle.objects.all()

    return render(
        request=request,
        template_name="automotive/log.html",
        context={
            'services': services,
            'vehicles': vehicles
        }
    )


@login_required
def export_to_excel(request):
    services = Service.objects.all().values(
        'id',
        'service_date',
        'link',
        'make__year',
        'make__make',
        'make__model',
        'dealership__name',
        'work_performed',
        'service_advisor__first_name',
        'service_advisor__last_name',
        'mileage',
        'cost',
        'comments'
    )
    file_date_str = datetime.datetime.now().strftime('%Y%m%d')
    return ExcelResponse(
        data=services,
        output_filename=f'services_{file_date_str}',
        worksheet_name="services"
    )


@login_required
def logout_request(request):
    logger.info(f'{request.user} logged out.')
    logout(request)
    messages.success(request, 'You were successfully logged out.')
    return redirect('automotive:index')

project/templates/automotive/add_service.html
{% extends 'automotive/autos_base.html' %}
{% block title %}Add Service{% endblock %}
{% block body %}
{% load static %}
<div class="container">
    <header class="page-heading">
        <h1>Add Service</h1>
    </header>
    <hr>
    <form class="form" method="POST">
        {%csrf_token%}
        <div class="form-group">
            <div class="row">
                <div class="col-sm-3">
                    <label for="service_date">Service Date:</label>
                    <input
                        type="date"
                        class="form-control form-control-sm"
                        data-date-format="mm/dd/yyyy"
                        id="service_date"
                        name="service_date"
                        required="true"
                    />
                </div>
                <div class="col-sm-9">
                    <label for="link">Dropbox Link:</label>
                    <input
                        class="form-control form-control-sm"
                        type="text"
                        id="link"
                        name="link"
                    />
                </div>
            </div> <!-- end row -->
            <div class="row">
                <div class="col-sm-6">
                    <label for="make">Make</label>
                    <select
                        class="form-control form-control-sm"
                        id="make"
                        name="make"
                        required="true"
                    />
                        <option
                        selected="true"
                        value="-1"
                        disabled
                        >
                            Select a Vehicle
                        </option>
                        {% for vehicle in vehicles %}
                        <option value="{{ vehicle.id}}">
                            {{ vehicle.year}} {{ vehicle.make}} {{ vehicle.model}}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-sm-6">
                        <label for="dealership">Dealership</label>
                        <select
                            class="form-control form-control-sm"
                            id="dealership"
                            name="dealership"
                            required="true"
                        >
                            <option
                            selected="true"
                            value="-1"
                            disabled
                            >
                                Select a Dealership
                            </option>
                            {% for dealership in dealerships %}
                            <option value="{{ dealership.id}}">
                                {{ dealership.name}}
                                </option>
                            {% endfor %}
                        </select>
                    </div>
                    </div>  <!-- end row -->
                    {% if form.make.errors or form.dealership.errors %}
                    <div class="row">
                        <div class="col-sm-6 err">
                            {% for error in form.make.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                        <div class="col-sm-6 err">
                            {% for error in form.dealership.errors %}
                                {{ error|escape }}
                            {% endfor %}
                        </div>
                    </div>  <!-- end row -->
                    {% endif %}
                    <div class="row">
                        <div class="col-sm-12">
                            <label for="work_performed">Work Performed:</label>
                            <textarea
                                class="form-control form-control-sm textarea"
                                id="work_performed"
                                name="work_performed"
                                row="10"
                            >
                            </textarea>
                        </div>
                        </div>  <!-- end row -->
                        {% if form.work_performed.errors %}
                        <div class="row">
                            <div class="col-sm-12 err">
                                {% for error in form.work_performed.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </div>
                        </div>  <!-- end row -->
                        {% endif %}
                        <div class="row">
                            <div class="col-sm-6">
                                    <label for="service_advisor">Service Advisor:</label>
                                    <select
                                        class="form-control form-control-sm"
                                        id="service_advisor"
                                        name="service_advisor"
                                        required="true"
                                    >
                                        <option
                                        selected="true"
                                        value="-1"
                                        disabled
                                        >
                                            Select a Service Advisor
                                        </option>
                                        {% for advisor in advisors %}
                                        <option value="{{ advisor.id}}">
                                            {{ advisor.first_name}} {{advisor.last_name}}
                                            </option>
                                        {% endfor %}
                                    </select>
                            </div>
                            <div class="col-sm-3">
                                    <label for="mileage">Mileage:</label>
                                    <input
                                        type="number"
                                        class="form-control form-control-sm"
                                        id="mileage"
                                        name="mileage"
                                        value="0"
                                    />
                            </div>
                            <div class="col-sm-3">
                                    <label for="cost">Service Cost:</label>
                                    <div class="input-group-append input-group-sm">
                                        <span class="form-control-sm input-group-text input-group-sm">$</span>
                                    <input
                                        type="number"
                                        class="form-control form-control-sm"
                                        id="cost"
                                        name="cost"
                                        step=".01"
                                        value="0"
                                    />
                                </div>
                            </div>
                        </div>  <!-- end row -->
                        {% if form.service_advisor.errors %}
                        <div class="row">
                            <div class="col-sm-6 err">
                                {% for error in form.service_advisor.errors %}
                                    {{ error|escape }}
                                {% endfor %}
                            </div>
                        </div>  <!-- end row -->
                        {% endif %}
                        <div class="row">
                        <div class="col-sm-12">
                            <label for="comments">Comments:</label>
                            <textarea
                                class="form-control form-control-sm textarea"
                                id="comments"
                                name="comments"
                                row="10"
                            />
                            </textarea>
                        </div>
                    </div> <!-- end row -->
                </div> <!-- end form group -->
                <br>
                <div class="form-group">
                    <button
                        class="btn btn-sm btn-primary"
                        id="add_svc_btn"
                        type="submit"
                        >
                            Submit
                    </button>
                    <button
                        class="btn btn-sm btn-secondary"
                        onclick="javascript:history.back()"
                    >
                        Cancel
                    </button>
                </div>
    </form>
</div>
{% endblock %}

project/templates/automotive/autos_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"
    ></script>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/png" href="{% static 'automotive/img/favicon.ico' %}" >

    <link rel="stylesheet" href="{% static 'automotive/css/styles.css' %}">

  <title>
    {% block title %} Base {% endblock %}
  </title>
  </head>

  <body>
    <div class="container-fluid"> <!-- container-fluid class-->

      <!-- Page Content -->
      {% include 'automotive/includes/_navbar.html' %}
      {% include 'automotive/includes/_messages.html' %}
      {% include 'automotive/includes/_form_errors.html' %}
      {% block body %}
      {% endblock %}<!-- End Page Content -->

    </div> <!-- End container-fluid class-->

    <script type="text/Javascript">
      setTimeout(function() {
        //Closing the alert
        $('.alert').alert('close');
      }, 5000);
    </script>

  </body>
</html>

project/templates/automotive/index.html
{% extends 'automotive/autos_base.html' %}
{% block title %}Autos Home{% endblock %}
{% block body %}
{% load static %}
<div>
    <main role="main">
            <header class="page-heading">
                <h1>Automotive Home</h1>
            </header>
            <section class="page-content">
                    <div class="grid-container">
                        <div id="max">
                            <img
                            src="{% static  'automotive/img/max.png' %}"
                            alt="2016 Nissan Maxima"
                            class="responsive"
                            />
                        </div>
                        <div id="bmw">
                            <img
                            src="{% static  'automotive/img/bmw.png' %}"
                            alt="2014 BMW 535I xDrive"
                            class="responsive"
                            />
                        </div>
                    </div>
            </section>
        </main>
</div>
{% endblock %}

project/templates/automotive/log.html
{% extends 'automotive/autos_base.html' %}
{% block title %}Autos Log{% endblock %}
{% block body %}
{% load static %}
    <div class="container-fluid">
      <header class="page-heading">
          <h1>Automotive Log</h1>
      </header>
      <hr>
      <div class="row">
          <div class="col-sm-3">
              <a href="{% url 'automotive:export_to_excel' %}" class="btn btn-dark btn-sm">
                  Export to Excel
              </a>
          </div>
      </div>
      <hr>
      <form>
          <div class="form-group row">
              <label for="car" class="col-sm-2 col-form-label">Filter by Vehicle</label>
              <div class="col-sm-3 select-update">
                  <select
                      class="form-control form-control-sm"
                      id="car"
                      name="car"
                      onchange="location = this.value;"
                  >
                      <option
                      selected="true"
                      value="Select a Vehicle"
                      disabled
                      >
                          Select a Vehicle
                      </option>
                      <option value="{% url 'automotive:log' %}">
                          All Vehicles
                      </option>
                      {% for vehicle in vehicles %}
                          <option value="{% url 'automotive:vehicle_filter'  vehicle.id %}">
                                {{vehicle.year}} {{vehicle.make}} {{vehicle.model}}
                          </option>
                      {% endfor %}
                  </select>
              </div>
            </div>
        </form>
      <br />
        <table class="table table-striped table-responsive-sm table-bordered">
        	<tr>
        		<th class="fit">ID</th>
    			<th class="fit">Service Date</th>
    			<th class="fit">Document</th>
        		<th class="fit">Make</th>
        		<th class="fit">Dealership</th>
        		<th class="fit">Service</th>
        		<th class="fit">Service Advisor</th>
        		<th class="fit">Mileage</th>
    			<th class="fit">Cost</th>
    			<th class="fit">Comments</th>
                <th class="fit">Edit</th>
        	</tr>
        	{% for service in services %}
        		<tr>
        			<td class="fit">{{service.id}}</td>
    				<td class="fit">{{service.service_date}}</td>
                    {% if service.link %}
    				    <td class="fit">
                            <a href="{{service.link}}" target="_blank">
                                View
                            </a>
                        </td>
                    {% else %}
                        <td class="fit">
                            <p>
                                No File
                            </p>
                        </td>
                    {% endif %}
            			<td class="fit">{{service.make}}</td>
            			<td class="fit">{{service.dealership}}</td>
            			<td class="fit">{{service.work_performed}}</td>
            			<td class="fit">{{service.service_advisor}}</td>
            			<td class="fit">{{service.mileage}}</td>
        				<td class="fit" id="service_cost">${{service.cost|floatformat:2}}</td>
        				<td class="fit">{{service.comments}}</td>
                        <td class="fit">
                            <a href="edit_service/{{service.id}}" class="btn btn-primary btn-sm">
                                Edit
                            </a>
                        </td>
        		</tr>
        	{% endfor %}
        </table>
        <br>
        <nav aria-label="Page navigation">
          <ul class="pagination  pagination-sm">

              {% if services.has_previous %}

                <li class="page-item">
                    <a class="page-link" href="?page=1">
                        &laquo First
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ services.previous_page_number }}">
                        Previous
                    </a>
                </li>

              {% endif %}

              <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1" aria-disabled="true">
                      Page {{ services.number }} of {{ services.paginator.num_pages }}
                  </a>
              </li>

              {% if services.has_next %}

                <li class="page-item">
                    <a class="page-link" href="?page={{services.next_page_number}}">
                        Next
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ services.paginator.num_pages }}">
                        Last &raquo
                    </a>
                </li>

              {% endif %}

          </ul>
        </nav>
    <div>
{% endblock %}

project/templates/automotive/login_automotive.html
{% extends 'automotive/autos_base.html' %}
{% load crispy_forms_tags %}
{% block body %}
{% load static %}
 <div class="container-fluid"> 
 <header class="page-heading">
   <h1>Automotive Login</h1>
 </header>
 <hr>
  <form method="POST">
            {% csrf_token %}
            <div class="form-group"></div>
                <label for="username">Username</label>
                <input type="text" class="form-control" name="username" id="username" required=true>
            <div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" id="password" required=true>
            </div>
            <button class="btn btn-sm btn-primary" type="submit">Login</button>
        </form>
 </div>
{% endblock %}